import type { SpellingItem } from '../../types'

// Age 7-9 spelling words, ordered easy -> hard so new words are introduced
// gently. Definitions and examples are kid-simple. Homophones are avoided so a
// heard word maps to one spelling.
const raw: Omit<SpellingItem, 'id'>[] = [
  { word: 'friend', definition: 'A person you like and enjoy being with.', example: 'My friend came over to play.' },
  { word: 'because', definition: 'For the reason that.', example: 'I smiled because I was happy.' },
  { word: 'people', definition: 'More than one person.', example: 'Many people came to the park.' },
  { word: 'school', definition: 'A place where you go to learn.', example: 'We read books at school.' },
  { word: 'happy', definition: 'Feeling good and cheerful.', example: 'She was happy on her birthday.' },
  { word: 'family', definition: 'The people you live with and love.', example: 'My family eats dinner together.' },
  { word: 'animal', definition: 'A living thing that can move, like a dog or cat.', example: 'A lion is a wild animal.' },
  { word: 'water', definition: 'The clear liquid we drink.', example: 'I drank a glass of water.' },
  { word: 'again', definition: 'One more time.', example: "Let's play that game again." },
  { word: 'little', definition: 'Small in size.', example: 'The little puppy fell asleep.' },
  { word: 'pretty', definition: 'Nice to look at.', example: 'She drew a pretty flower.' },
  { word: 'funny', definition: 'Something that makes you laugh.', example: 'The clown was very funny.' },
  { word: 'yellow', definition: 'The color of the sun.', example: 'I have a yellow raincoat.' },
  { word: 'always', definition: 'Every time; all the time.', example: 'I always brush my teeth.' },
  { word: 'morning', definition: 'The early part of the day.', example: 'We eat breakfast in the morning.' },
  { word: 'garden', definition: 'A place where plants grow.', example: 'Roses bloom in the garden.' },
  { word: 'winter', definition: 'The cold season of the year.', example: 'It snows in winter.' },
  { word: 'number', definition: 'A word like one, two, or three.', example: 'Pick a number from one to ten.' },
  { word: 'picture', definition: 'A drawing or a photo.', example: 'She painted a picture of a cat.' },
  { word: 'beautiful', definition: 'Very pretty.', example: 'The sunset was beautiful.' },
  { word: 'favorite', definition: 'The one you like best.', example: 'Pizza is my favorite food.' },
  { word: 'surprise', definition: 'Something you did not expect.', example: 'The party was a big surprise.' },
  { word: 'elephant', definition: 'A huge gray animal with a long trunk.', example: 'The elephant sprayed water.' },
  { word: 'dinosaur', definition: 'A giant animal that lived long ago.', example: 'The dinosaur had sharp teeth.' },
  { word: 'butterfly', definition: 'An insect with big colorful wings.', example: 'A butterfly landed on the flower.' },
  { word: 'birthday', definition: 'The day you were born, celebrated each year.', example: 'I get cake on my birthday.' },
  { word: 'chocolate', definition: 'A sweet brown treat.', example: 'She loves chocolate ice cream.' },
  { word: 'important', definition: 'Mattering a lot.', example: 'Sleep is important for you.' },
  { word: 'different', definition: 'Not the same.', example: 'We chose different colors.' },
  { word: 'together', definition: 'With each other.', example: 'We worked together on the puzzle.' },
  { word: 'something', definition: 'A thing you do not name.', example: 'I have something to tell you.' },
  { word: 'remember', definition: 'To keep in your mind.', example: 'Remember to feed the dog.' },
  { word: 'question', definition: 'Something you ask.', example: 'She asked a good question.' },
  { word: 'calendar', definition: 'A chart of the days and months.', example: 'I marked my birthday on the calendar.' },
  { word: 'sentence', definition: 'A group of words that makes a complete thought.', example: 'Write one sentence about your day.' },
  { word: 'vacation', definition: 'A trip or time off for fun.', example: 'We went to the beach on vacation.' },
  { word: 'mountain', definition: 'A very tall, rocky hill.', example: 'Snow covered the mountain.' },
  { word: 'hospital', definition: 'A place where doctors help sick people.', example: 'The nurse works at the hospital.' },
  { word: 'library', definition: 'A place full of books to borrow.', example: 'I returned my book to the library.' },
  { word: 'necessary', definition: 'Needed.', example: 'Water is necessary for life.' },
  { word: 'separate', definition: 'To keep apart.', example: 'Separate the red blocks from the blue ones.' },
  { word: 'weird', definition: 'Strange or unusual.', example: 'The juice had a weird taste.' },
  { word: 'receive', definition: 'To get something.', example: 'I will receive a gift.' },
  { word: 'believe', definition: 'To think something is true.', example: 'I believe you can do it.' },
  { word: 'piece', definition: 'A part of something.', example: 'Can I have a piece of cake?' },
  { word: 'special', definition: 'Better or different in a good way.', example: 'Today is a special day.' },
  { word: 'strange', definition: 'Odd or unfamiliar.', example: 'We heard a strange noise.' },
  { word: 'thought', definition: 'An idea in your mind.', example: 'I had a great thought.' },
  { word: 'enough', definition: 'As much as you need.', example: 'We have enough chairs.' },
  { word: 'through', definition: 'From one side to the other.', example: 'The train went through the tunnel.' },
  { word: 'island', definition: 'Land with water all around it.', example: 'We sailed to a small island.' },
  { word: 'castle', definition: 'A big stone home for a king or queen.', example: 'The castle had tall towers.' },
  { word: 'knife', definition: 'A tool used to cut.', example: 'Use a knife to cut the apple.' },
  { word: 'listen', definition: 'To pay attention to sound.', example: 'Listen to the music.' },
  { word: 'science', definition: 'The study of how the world works.', example: 'We did a science experiment.' },
  { word: 'character', definition: 'A person in a story.', example: 'My favorite character is brave.' },
  { word: 'February', definition: 'The second month of the year.', example: "Valentine's Day is in February." },
  { word: 'Wednesday', definition: 'The day after Tuesday.', example: 'We have art class on Wednesday.' },
  { word: 'neighbor', definition: 'A person who lives near you.', example: 'My neighbor has a friendly dog.' },
]

export const SPELLING_WORDS: SpellingItem[] = raw.map((w) => ({ ...w, id: `spell:${w.word.toLowerCase()}` }))

export const SPELLING_BY_ID: Record<string, SpellingItem> = Object.fromEntries(
  SPELLING_WORDS.map((w) => [w.id, w]),
)
