import type { SpellingItem } from '../../types'

// Ages 10-15 spelling words: commonly-misspelled and spelling-bee style words,
// ordered roughly easy -> hard. Definitions are clear; examples short.
// Homophones are avoided so a heard word maps to one spelling.
const raw: Omit<SpellingItem, 'id'>[] = [
  { word: 'rhythm', definition: 'A regular, repeated pattern of sound or movement.', example: 'We clapped to the rhythm of the song.' },
  { word: 'separate', definition: 'To set or keep apart.', example: 'Separate the recycling from the trash.' },
  { word: 'definitely', definition: 'Without any doubt.', example: 'I will definitely be there.' },
  { word: 'embarrass', definition: 'To make someone feel awkward or ashamed.', example: "Please don't embarrass me at the party." },
  { word: 'necessary', definition: 'Needed; required.', example: 'Sleep is necessary for good health.' },
  { word: 'occasionally', definition: 'Now and then; sometimes.', example: 'We occasionally visit the museum.' },
  { word: 'recommend', definition: 'To suggest as good or worthwhile.', example: 'I recommend this book to everyone.' },
  { word: 'restaurant', definition: 'A place where meals are served to customers.', example: 'We ate dinner at a new restaurant.' },
  { word: 'noticeable', definition: 'Easy to see or notice.', example: 'There was a noticeable change in the weather.' },
  { word: 'privilege', definition: 'A special right or advantage.', example: 'Driving is a privilege, not a right.' },
  { word: 'mischievous', definition: 'Playfully causing trouble.', example: 'The mischievous puppy hid my shoe.' },
  { word: 'exaggerate', definition: 'To make something seem larger or greater than it is.', example: "Don't exaggerate how far we walked." },
  { word: 'independent', definition: 'Not relying on others.', example: 'She is very independent for her age.' },
  { word: 'knowledge', definition: 'Information and understanding gained by learning.', example: 'Reading builds your knowledge.' },
  { word: 'guarantee', definition: 'A firm promise that something will happen.', example: 'They guarantee fast delivery.' },
  { word: 'obstacle', definition: 'Something that blocks the way or progress.', example: 'He leaped over the obstacle.' },
  { word: 'sufficient', definition: 'Enough for a purpose.', example: 'We had sufficient food for the trip.' },
  { word: 'thorough', definition: 'Complete and careful.', example: 'She did a thorough job cleaning the lab.' },
  { word: 'occurrence', definition: 'Something that happens; an event.', example: 'A solar eclipse is a rare occurrence.' },
  { word: 'maintenance', definition: 'The act of keeping something in good condition.', example: 'The bridge needs regular maintenance.' },
  { word: 'acquire', definition: 'To get or gain something.', example: 'He hopes to acquire new coding skills.' },
  { word: 'pronunciation', definition: 'The way a word is spoken.', example: 'She practiced the correct pronunciation.' },
  { word: 'conscience', definition: 'The inner sense of what is right and wrong.', example: 'His conscience told him to apologize.' },
  { word: 'perseverance', definition: 'Continuing to try despite difficulty.', example: 'Her perseverance helped her finish the race.' },
  { word: 'questionnaire', definition: 'A set of written questions used to gather information.', example: 'Please complete the questionnaire.' },
  { word: 'entrepreneur', definition: 'A person who starts and runs a business.', example: 'The young entrepreneur opened a bakery.' },
  { word: 'accommodate', definition: 'To provide room for or to adjust to fit.', example: 'The hotel can accommodate 300 guests.' },
  { word: 'committee', definition: 'A group of people chosen to do a task.', example: 'The committee planned the school fair.' },
  { word: 'cemetery', definition: 'A place where the dead are buried.', example: 'We left flowers at the cemetery.' },
  { word: 'colleague', definition: 'A person you work with.', example: 'My colleague helped with the report.' },
  { word: 'dilemma', definition: 'A difficult choice between two options.', example: 'She faced a tricky dilemma.' },
  { word: 'fascinate', definition: 'To attract and hold the interest of.', example: 'Stories about space fascinate me.' },
  { word: 'negotiate', definition: 'To discuss in order to reach an agreement.', example: 'They will negotiate a fair price.' },
  { word: 'parallel', definition: 'Side by side and always the same distance apart.', example: 'The train tracks run parallel.' },
  { word: 'quarantine', definition: 'To keep apart to stop an illness from spreading.', example: 'The new fish stayed in quarantine for a week.' },
  { word: 'reservoir', definition: 'A large natural or artificial store of water.', example: 'The city draws water from a reservoir.' },
  { word: 'silhouette', definition: 'A dark outline seen against a lighter background.', example: 'We saw the silhouette of the hills at dusk.' },
  { word: 'unanimous', definition: 'Agreed to by everyone.', example: 'The vote was unanimous.' },
  { word: 'amateur', definition: 'A person who does something for enjoyment, not money.', example: 'She is an amateur photographer.' },
  { word: 'beneficial', definition: 'Producing good results; helpful.', example: 'Exercise is beneficial to your health.' },
  { word: 'catastrophe', definition: 'A sudden, terrible disaster.', example: 'The flood was a catastrophe for the town.' },
  { word: 'desperate', definition: 'Feeling hopeless and ready to do anything.', example: 'They made a desperate attempt to escape.' },
  { word: 'enthusiasm', definition: 'A strong feeling of excitement and interest.', example: 'She showed great enthusiasm for art.' },
  { word: 'hierarchy', definition: 'A system in which people or things are ranked by level.', example: 'Ants live in a strict hierarchy.' },
  { word: 'conscientious', definition: 'Careful, thorough, and responsible.', example: 'He is a conscientious student.' },
  { word: 'millennium', definition: 'A period of one thousand years.', example: 'A new millennium began in the year 2001.' },
  { word: 'vacuum', definition: 'A space with no air; also a machine that cleans floors.', example: 'He ran the vacuum across the carpet.' },
  { word: 'lieutenant', definition: 'An officer rank in the military or police.', example: 'The lieutenant gave the orders.' },
  { word: 'mediocre', definition: 'Only average; not very good.', example: 'The sequel was mediocre.' },
  { word: 'jewelry', definition: 'Decorative items such as rings and necklaces.', example: 'She wore sparkling jewelry.' },
  { word: 'xylophone', definition: 'A musical instrument with wooden bars you strike.', example: 'She played a tune on the xylophone.' },
  { word: 'fluorescent', definition: 'Giving off bright light when lit.', example: 'The poster glowed with fluorescent colors.' },
  { word: 'zealous', definition: 'Very enthusiastic and eager.', example: 'He was a zealous supporter of the team.' },
  { word: 'yacht', definition: 'A medium-to-large boat used for pleasure trips.', example: 'They sailed along the coast on a yacht.' },
  { word: 'apparent', definition: 'Clearly seen or understood; obvious.', example: 'It was apparent that she had practiced.' },
  { word: 'persuade', definition: 'To convince someone to do or believe something.', example: 'He tried to persuade us to come along.' },
  { word: 'sincerely', definition: 'In an honest and genuine way.', example: 'She sincerely thanked the volunteers.' },
  { word: 'tongue', definition: 'The movable muscle in the mouth used to taste and talk.', example: 'He burned his tongue on the hot soup.' },
  { word: 'vengeance', definition: 'Punishment given in return for a wrong.', example: 'The story’s hero sought vengeance.' },
]

export const SPELLING_WORDS: SpellingItem[] = raw.map((w) => ({ ...w, id: `spell:${w.word.toLowerCase()}` }))

export const SPELLING_BY_ID: Record<string, SpellingItem> = Object.fromEntries(
  SPELLING_WORDS.map((w) => [w.id, w]),
)
